///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestProject1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNewEntry recording.
    /// </summary>
    [TestModule("5b8b1242-827f-494a-a39b-64548c8e7770", ModuleType.Recording, 1)]
    public partial class AddNewEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestProject1Repository repository.
        /// </summary>
        public static TestProject1Repository repo = TestProject1Repository.Instance;

        static AddNewEntry instance = new AddNewEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNewEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNewEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.AddEntry' at 7;14.", repo.MainForm.AddEntryInfo, new RecordItemIndex(0));
            repo.MainForm.AddEntry.Click("7;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Text' at 67;7.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(1));
            repo.PwEntryForm.MTabEntry.Text.Click("67;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(2));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P{LShiftKey up}roject' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(3));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("P{LShiftKey up}roject");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Space}{LShiftKey down}T{LShiftKey up}itle{Space}' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(4));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("{Space}{LShiftKey down}T{LShiftKey up}itle{Space}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(5));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.MBtnIcon' at 14;10.", repo.PwEntryForm.MTabEntry.MBtnIconInfo, new RecordItemIndex(6));
            repo.PwEntryForm.MTabEntry.MBtnIcon.Click("14;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'IconPickerForm.ListItem33' at 22;11.", repo.IconPickerForm.ListItem33Info, new RecordItemIndex(7));
            repo.IconPickerForm.ListItem33.DoubleClick("22;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.UserName' at 62;7.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(8));
            repo.PwEntryForm.MTabEntry.UserName.Click("62;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}A{LShiftKey up}mit.{LShiftKey down}A{LShiftKey up}swani{Tab}amit{Tab}' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(9));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys("{LShiftKey down}A{LShiftKey up}mit.{LShiftKey down}A{LShiftKey up}swani{Tab}amit{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}amit{Tab}{Tab}www.'.", new RecordItemIndex(10));
            Keyboard.Press("{Tab}amit{Tab}{Tab}www.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ut{Back}{Back}outlook.com{Tab}{LShiftKey down}T{LShiftKey up}his{Space}is{Space}for{Space}{LShiftKey down}T{LShiftKey up}etin{Back}{Back}{Back}sting{Space}{LShiftKey down}P{LShiftKey up}urponse{Back}{Back}{Back}se.'.", new RecordItemIndex(11));
            Keyboard.Press("ut{Back}{Back}outlook.com{Tab}{LShiftKey down}T{LShiftKey up}his{Space}is{Space}for{Space}{LShiftKey down}T{LShiftKey up}etin{Back}{Back}{Back}sting{Space}{LShiftKey down}P{LShiftKey up}urponse{Back}{Back}{Back}se.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 39;15.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(12));
            repo.PwEntryForm.MBtnOK.Click("39;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Save' at 12;7.", repo.MainForm.SaveInfo, new RecordItemIndex(13));
            repo.MainForm.Save.Click("12;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
