///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("c8810d3b-7a58-48ef-b61c-5363d1ff7610")]
    public partial class Test1Repository : RepoGenBaseFolder
    {
        static Test1Repository instance = new Test1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Test1Repository element repository.
        /// </summary>
        [RepositoryFolder("c8810d3b-7a58-48ef-b61c-5363d1ff7610")]
        public static Test1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test1Repository() 
            : base("Test1Repository", "/", null, 0, false, "c8810d3b-7a58-48ef-b61c-5363d1ff7610", ".\\RepositoryImages\\Test1Repositoryc8810d3b.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c8810d3b-7a58-48ef-b61c-5363d1ff7610")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Test1RepositoryFolders
    {
    }
#pragma warning restore 0436
}