///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNewEntry recording.
    /// </summary>
    [TestModule("dd8de5cd-650a-4611-9752-ef9b56f87ba8", ModuleType.Recording, 1)]
    public partial class AddNewEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test1Repository repository.
        /// </summary>
        public static Test1Repository repo = Test1Repository.Instance;

        static AddNewEntry instance = new AddNewEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNewEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNewEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.AddEntry' at 9;9.", repo.MainForm.AddEntryInfo, new RecordItemIndex(0));
            repo.MainForm.AddEntry.Click("9;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Text' at 6;6.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(1));
            repo.PwEntryForm.MTabEntry.Text.Click("6;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(2));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P{LShiftKey up}' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(3));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("P{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'roject{Space}{LShiftKey}1' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(4));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("roject{Space}{LShiftKey}1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.MBtnIcon' at 10;12.", repo.PwEntryForm.MTabEntry.MBtnIconInfo, new RecordItemIndex(5));
            repo.PwEntryForm.MTabEntry.MBtnIcon.Click("10;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'IconPickerForm.ListItem12' at 17;9.", repo.IconPickerForm.ListItem12Info, new RecordItemIndex(6));
            repo.IconPickerForm.ListItem12.DoubleClick("17;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.UserName' at 31;12.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(7));
            repo.PwEntryForm.MTabEntry.UserName.Click("31;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}A{LShiftKey up}mit.{LShiftKey down}A{LShiftKey up}swani{Tab}amit{Tab}{Tab}ait' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(8));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys("{LShiftKey down}A{LShiftKey up}mit.{LShiftKey down}A{LShiftKey up}swani{Tab}amit{Tab}{Tab}ait");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}amit{Tab}{Tab}www.gmail.com{Tab}{LShiftKey down}T{LShiftKey up}his{Space down}i{Space up}s{Space}for{Space}{LShiftKey down}T{LShiftKey up}estig{Back}ng{Space}{LShiftKey down}P{LShiftKey up}urpose'.", new RecordItemIndex(9));
            Keyboard.Press("{Back}{Back}{Back}{Back}amit{Tab}{Tab}www.gmail.com{Tab}{LShiftKey down}T{LShiftKey up}his{Space down}i{Space up}s{Space}for{Space}{LShiftKey down}T{LShiftKey up}estig{Back}ng{Space}{LShiftKey down}P{LShiftKey up}urpose");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 45;6.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(10));
            repo.PwEntryForm.MBtnOK.Click("45;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Save' at 10;11.", repo.MainForm.SaveInfo, new RecordItemIndex(11));
            repo.MainForm.Save.Click("10;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
