///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewProject1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNewEntry recording.
    /// </summary>
    [TestModule("1c5ef5a9-9422-4061-85b3-3ad8dc4114b4", ModuleType.Recording, 1)]
    public partial class AddNewEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewProject1Repository repository.
        /// </summary>
        public static NewProject1Repository repo = NewProject1Repository.Instance;

        static AddNewEntry instance = new AddNewEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNewEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNewEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.AddEntry' at 11;4.", repo.MainForm.AddEntryInfo, new RecordItemIndex(0));
            repo.MainForm.AddEntry.Click("11;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.Text' at 59;6.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(1));
            repo.PwEntryForm.MTabEntry.Text.Click("59;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey up}itle' with focus on 'PwEntryForm.MTabEntry.Text'.", repo.PwEntryForm.MTabEntry.TextInfo, new RecordItemIndex(2));
            repo.PwEntryForm.MTabEntry.Text.PressKeys("{LShiftKey down}T{LShiftKey up}itle");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.MBtnIcon' at 22;10.", repo.PwEntryForm.MTabEntry.MBtnIconInfo, new RecordItemIndex(3));
            repo.PwEntryForm.MTabEntry.MBtnIcon.Click("22;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'IconPickerForm.ListItem33' at 19;10.", repo.IconPickerForm.ListItem33Info, new RecordItemIndex(4));
            repo.IconPickerForm.ListItem33.DoubleClick("19;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MTabEntry.UserName' at 40;12.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(5));
            repo.PwEntryForm.MTabEntry.UserName.Click("40;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}A{LShiftKey up}mit.{LShiftKey down}A{LShiftKey up}swani' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(6));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys("{LShiftKey down}A{LShiftKey up}mit.{LShiftKey down}A{LShiftKey up}swani");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}amit{Tab}{Tab}amit{Tab}{Tab}www.gmail.com{Tab}{LShiftKey down}T{LShiftKey up}his{Space down}i{Space up}s{Space}' with focus on 'PwEntryForm.MTabEntry.UserName'.", repo.PwEntryForm.MTabEntry.UserNameInfo, new RecordItemIndex(7));
            repo.PwEntryForm.MTabEntry.UserName.PressKeys("{Tab}amit{Tab}{Tab}amit{Tab}{Tab}www.gmail.com{Tab}{LShiftKey down}T{LShiftKey up}his{Space down}i{Space up}s{Space}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey}for{Space down}{LShiftKey down}{Space up}T{LShiftKey up}esting{Space}puro{Back}pose'.", new RecordItemIndex(8));
            Keyboard.Press("{LShiftKey}for{Space down}{LShiftKey down}{Space up}T{LShiftKey up}esting{Space}puro{Back}pose");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PwEntryForm.MBtnOK' at 58;7.", repo.PwEntryForm.MBtnOKInfo, new RecordItemIndex(9));
            repo.PwEntryForm.MBtnOK.Click("58;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Save' at 8;11.", repo.MainForm.SaveInfo, new RecordItemIndex(10));
            repo.MainForm.Save.Click("8;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
