///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NewProject1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NewProject1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("ba2d8fad-c055-4cec-9fd6-8ecbd36eb38f")]
    public partial class NewProject1Repository : RepoGenBaseFolder
    {
        static NewProject1Repository instance = new NewProject1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the NewProject1Repository element repository.
        /// </summary>
        [RepositoryFolder("ba2d8fad-c055-4cec-9fd6-8ecbd36eb38f")]
        public static NewProject1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NewProject1Repository() 
            : base("NewProject1Repository", "/", null, 0, false, "ba2d8fad-c055-4cec-9fd6-8ecbd36eb38f", ".\\RepositoryImages\\NewProject1Repositoryba2d8fad.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ba2d8fad-c055-4cec-9fd6-8ecbd36eb38f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class NewProject1RepositoryFolders
    {
    }
#pragma warning restore 0436
}