///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test44
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test44Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("396596d7-ce57-4092-a731-0dfafc85d123")]
    public partial class Test44Repository : RepoGenBaseFolder
    {
        static Test44Repository instance = new Test44Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Test44Repository element repository.
        /// </summary>
        [RepositoryFolder("396596d7-ce57-4092-a731-0dfafc85d123")]
        public static Test44Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test44Repository() 
            : base("Test44Repository", "/", null, 0, false, "396596d7-ce57-4092-a731-0dfafc85d123", ".\\RepositoryImages\\Test44Repository396596d7.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("396596d7-ce57-4092-a731-0dfafc85d123")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Test44RepositoryFolders
    {
    }
#pragma warning restore 0436
}