///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FirstProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FirstProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("8545c898-7f29-4ab5-bf85-60825452de08")]
    public partial class FirstProjectRepository : RepoGenBaseFolder
    {
        static FirstProjectRepository instance = new FirstProjectRepository();

        /// <summary>
        /// Gets the singleton class instance representing the FirstProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("8545c898-7f29-4ab5-bf85-60825452de08")]
        public static FirstProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FirstProjectRepository() 
            : base("FirstProjectRepository", "/", null, 0, false, "8545c898-7f29-4ab5-bf85-60825452de08", ".\\RepositoryImages\\FirstProjectRepository8545c898.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8545c898-7f29-4ab5-bf85-60825452de08")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class FirstProjectRepositoryFolders
    {
    }
#pragma warning restore 0436
}