///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("30891f41-9916-4d19-9968-95c3ef1fff84")]
    public partial class TestProjectRepository : RepoGenBaseFolder
    {
        static TestProjectRepository instance = new TestProjectRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TestProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("30891f41-9916-4d19-9968-95c3ef1fff84")]
        public static TestProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestProjectRepository() 
            : base("TestProjectRepository", "/", null, 0, false, "30891f41-9916-4d19-9968-95c3ef1fff84", ".\\RepositoryImages\\TestProjectRepository30891f41.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("30891f41-9916-4d19-9968-95c3ef1fff84")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class TestProjectRepositoryFolders
    {
    }
#pragma warning restore 0436
}