///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KeePass
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KeePassRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("42f4f834-bce3-47f9-8d83-e46090e5d45c")]
    public partial class KeePassRepository : RepoGenBaseFolder
    {
        static KeePassRepository instance = new KeePassRepository();

        /// <summary>
        /// Gets the singleton class instance representing the KeePassRepository element repository.
        /// </summary>
        [RepositoryFolder("42f4f834-bce3-47f9-8d83-e46090e5d45c")]
        public static KeePassRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KeePassRepository() 
            : base("KeePassRepository", "/", null, 0, false, "42f4f834-bce3-47f9-8d83-e46090e5d45c", ".\\RepositoryImages\\KeePassRepository42f4f834.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("42f4f834-bce3-47f9-8d83-e46090e5d45c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class KeePassRepositoryFolders
    {
    }
#pragma warning restore 0436
}