///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Project3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteEntry recording.
    /// </summary>
    [TestModule("e2f71738-8d02-416e-8d08-9efc13e62fef", ModuleType.Recording, 1)]
    public partial class DeleteEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Project3Repository repository.
        /// </summary>
        public static Project3Repository repo = Project3Repository.Instance;

        static DeleteEntry instance = new DeleteEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MainForm.Test' at 47;9.", repo.MainForm.TestInfo, new RecordItemIndex(0));
            repo.MainForm.Test.Click(System.Windows.Forms.MouseButtons.Right, "47;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MCtxPwList.DeleteEntry' at 109;14.", repo.MCtxPwList.DeleteEntryInfo, new RecordItemIndex(1));
            repo.MCtxPwList.DeleteEntry.Click("109;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.ButtonDelete' at 35;11.", repo.KeePass.ButtonDeleteInfo, new RecordItemIndex(2));
            repo.KeePass.ButtonDelete.Click("35;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Save' at 13;13.", repo.MainForm.SaveInfo, new RecordItemIndex(3));
            repo.MainForm.Save.Click("13;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
