///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Project3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Project3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("31971890-ced4-4047-91d4-ab50c7d58bf9")]
    public partial class Project3Repository : RepoGenBaseFolder
    {
        static Project3Repository instance = new Project3Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Project3Repository element repository.
        /// </summary>
        [RepositoryFolder("31971890-ced4-4047-91d4-ab50c7d58bf9")]
        public static Project3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Project3Repository() 
            : base("Project3Repository", "/", null, 0, false, "31971890-ced4-4047-91d4-ab50c7d58bf9", ".\\RepositoryImages\\Project3Repository31971890.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("31971890-ced4-4047-91d4-ab50c7d58bf9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Project3RepositoryFolders
    {
    }
#pragma warning restore 0436
}