///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Project2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Project2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("e4a5eb33-d93c-477e-8917-7b4cbdc1c6ad")]
    public partial class Project2Repository : RepoGenBaseFolder
    {
        static Project2Repository instance = new Project2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Project2Repository element repository.
        /// </summary>
        [RepositoryFolder("e4a5eb33-d93c-477e-8917-7b4cbdc1c6ad")]
        public static Project2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Project2Repository() 
            : base("Project2Repository", "/", null, 0, false, "e4a5eb33-d93c-477e-8917-7b4cbdc1c6ad", ".\\RepositoryImages\\Project2Repositorye4a5eb33.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e4a5eb33-d93c-477e-8917-7b4cbdc1c6ad")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Project2RepositoryFolders
    {
    }
#pragma warning restore 0436
}